/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeFunctions_NativeLib */

#ifndef _Included_nativeFunctions_NativeLib
#define _Included_nativeFunctions_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeFunctions_NativeLib
 * Method:    FindRectangle
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_FindRectangle
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    InitializedOpenCVGlobalVar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_InitializedOpenCVGlobalVar
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    InitialozeOpenCVGlobalVarByLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_InitialozeOpenCVGlobalVarByLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    SaveNewMarkerFrame
 * Signature: (JIIILnativeFunctions/FindMarkerAssist;)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_SaveNewMarkerFrame
  (JNIEnv *, jclass, jlong, jint, jint, jint, jobject);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    ComputeMarkerPosition
 * Signature: (LnativeFunctions/FindMarkerAssist;)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_ComputeMarkerPosition
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    saveAllMarkers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_saveAllMarkers
  (JNIEnv *, jclass);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    clearNonValidMarkerImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_clearNonValidMarkerImage
  (JNIEnv *, jclass);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    reComputeMarkerPosition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_reComputeMarkerPosition
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
