/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeFunctions_NativeLib */

#ifndef _Included_nativeFunctions_NativeLib
#define _Included_nativeFunctions_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeFunctions_NativeLib
 * Method:    FindRectangle
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_FindRectangle
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    saveCameraParam
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_saveCameraParam
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    startCalibrate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_startCalibrate
  (JNIEnv *, jclass);

/*
 * Class:     nativeFunctions_NativeLib
 * Method:    InitializedOpenCVGlobalVar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nativeFunctions_NativeLib_InitializedOpenCVGlobalVar
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
